version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_dev_mem
    environment:
      POSTGRES_DB: dev_mem
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d dev_mem"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dev_mem
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
