CREATE TABLE Author (
    id SERIAL PRIMARY KEY,
    full_name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE budget
ADD CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES Author(id) ON DELETE SET NULL;